### ISSUE TITLE
Unexpected error - Can't start streaming

### ISSUE THREAD

**Issue by Alabasterjones** [mixer/obs-studio-ftl#92]
So, I've been using the FTL version of obs studio for a while for streaming on beam.pro, but the last week or so, ever since the change from beam to mixer.com my stream has been unable to start, I get "An unexpected error occured when trying to conenct to the server. More informaion in the log file" I haven't made any changes myself, so I've got no clue what's going on and I don't know how to decipher the logs, could someone send some help my way?

https://gist.github.com/anonymous/cf486220984c0351b829f0e159a08dee

**Comment by sslivins** [comment]
can you go here and paste what you get back:

https://mixer.com/api/v1/ingests/best

**Comment by Alabasterjones** [comment]
[{"ip":"169.51.70.224","name":"ingest3.osl01.beam.pro"},{"ip":"169.51.70.206","name":"ingest1.osl01.beam.pro"},{"ip":"169.51.70.246","name":"ingest4.osl01.beam.pro"}]

**Comment by QuinnDamerell-MS** [comment]
Can you try pinging those servers (by ip) and see if you can talk to them?

**Comment by Alabasterjones** [comment]
[Seems like it's going through ](https://gyazo.com/ce1cc655b946ac3eb56110da4b8f597b)

**Comment by sslivins** [comment]
are you familiar with wireshark?  if so can you run that while attempting a connection again?

**Comment by sslivins** [comment]
can you also try our old uri https://beam.pro/api/v1/ingests/best

**Comment by Alabasterjones** [comment]
Hello, sorry for the slow response. I downloaded the program but I have no clue how to use it so I'd guess that's off the table. What I did today however is I tried using the regular obs-client to stream to mixer with the same key and there was no problem what so ever establishing a connection, so I doubt it's a network error, unless the ftl-client works very differently?

**Comment by sslivins** [comment]
okay, i have identified and fixed the issue.  the fix is rolling out to the ingests now...some of the oslo ingests are fixed otherwise the rest will be completely in the next hour

**Comment by LasiusNeglectus** [comment]
Do we have any further update regarding this as I also get the same error using OBS FTL which was last updated March.  Presumably all tested under mixer as it is no longer beam. Thanks for any assistance. " an unexpected error occurred when trying to connect to the server"

**Comment by sslivins** [comment]
the original fix didnt work correctly in a few scenarios.  please try again using 'auto'.  that will put you on a fixed server while i continue to roll out the fixes to the others

**Comment by LasiusNeglectus** [comment]
I did a work around of put key in OBS studio and then close that go back to
OBS FTL put key in and I've always used auto anyway. Or perhaps something
fixed in the background by yourself ?

On 31 May 2017 12:47 a.m., "sslivins" <notifications@github.com> wrote:

the original fix didnt work correctly in a few scenarios. please try again
using 'auto'. that will put you on a fixed server while i continue to roll
out the fixes to the others

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mixer/obs-studio-ftl/issues/92#issuecomment-305040542>,
or mute the thread

**Comment by Alabasterjones** [comment]
It would seem like the issue has gone from bad to worse on my end, now instead of waiting a couple of seconds before I get the error msg it gives me a new, but similar "Failed to connect to server" msg as soon as I hit the start streaming button, I've tried auto, all the closest servers around me and even servers in NA and Asia, still get the error message. I can still stream just fine with the regular obs client.

**Comment by Mitragliatrice** [comment]
I seem to be having this same issue. Any update on it? Thanks!

Log: https://gist.github.com/94fcb9b2b736236d7c98528c6c99a747

**Comment by Alabasterjones** [comment]
I just actually read my log file, and it seems I had put in the wrong stream key...

But I'm guessing I was experiencing the original issue that was fixed, and during the process of trying to fix it I reset my key and made a typo when pasting the new one. The original log file didn't have the "wrong key"-message. 

Thanks for the responses and the help, people that assisted!
